# Generated by Django 5.2.17 on 2026-09-10 13:04

import django.db.models.deletion
import dynamic_qr.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_code', models.CharField(db_index=True, default=dynamic_qr.models.generate_short_code, max_length=20, unique=True)),
                ('qr_name', models.CharField(help_text='A friendly name for this QR code', max_length=200)),
                ('qr_type', models.CharField(choices=[('url', 'URL / Link'), ('text', 'Text Content'), ('wifi', 'Wi-Fi Network'), ('location', 'Map / Location'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('tiktok', 'TikTok'), ('x-twitter', 'X / Twitter'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('pdf', 'PDF Document'), ('audio', 'Audio / MP3'), ('video', 'Video / MP4'), ('image', 'Image / Photo'), ('pptx', 'PowerPoint (PPTX)'), ('excel', 'Excel (XLSX)'), ('word', 'Word (DOCX)'), ('email', 'Email Address'), ('phone', 'Phone Call'), ('sms', 'SMS Message'), ('vcard', 'vCard (Contact)'), ('calendar', 'Calendar Event'), ('booking', 'Booking / Appt'), ('google-review', 'Google Review'), ('google-forms', 'Google Forms'), ('google-doc', 'Google Doc'), ('google-sheets', 'Google Sheets'), ('play-market', 'Play Market'), ('app-store', 'App Store'), ('paypal', 'PayPal'), ('etsy', 'Etsy Shop'), ('amazon', 'Amazon Product'), ('venmo', 'Venmo'), ('upi', 'UPI Payment'), ('crypto', 'Crypto Payment'), ('spotify', 'Spotify'), ('link-list', 'List of Links'), ('custom-url', 'Custom Short URL'), ('office-365', 'Office 365'), ('2d-barcode', '2D Barcode')], default='url', max_length=40)),
                ('destination_url', models.URLField(blank=True, help_text='Primary URL for direct redirect types', max_length=2000, null=True)),
                ('qr_data', models.JSONField(blank=True, default=dict, help_text='Structured data for non-URL QR types')),
                ('file_content', models.FileField(blank=True, help_text='File associated with PDF, Audio, Video, etc.', null=True, upload_to='dynamic_qr_contents/')),
                ('fg_color', models.CharField(default='#000000', max_length=10)),
                ('bg_color', models.CharField(default='#ffffff', max_length=10)),
                ('body_style', models.CharField(default='square', max_length=20)),
                ('eye_style', models.CharField(default='square', max_length=20)),
                ('ball_style', models.CharField(default='square', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dynamic_qr_logos/')),
                ('design_options', models.JSONField(blank=True, default=dict, help_text='Advanced design options like frames, text, error correction, etc.')),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('header', models.CharField(blank=True, help_text='Custom URL path segment before the short code', max_length=20, null=True)),
                ('qr_enabled', models.BooleanField(default=False, help_text='Generate a QR code linking to this short URL')),
                ('custom_alias', models.CharField(blank=True, db_index=True, help_text='Custom URL alias', max_length=50, null=True, unique=True)),
                ('domain', models.CharField(default='default', help_text='Domain used for the short URL', max_length=100)),
                ('password', models.CharField(blank=True, help_text='Hashed password for protected links', max_length=128, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='When the link expires', null=True)),
                ('require_gps', models.BooleanField(default=False, help_text='Require GPS location to access')),
                ('utm_enabled', models.BooleanField(default=False)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=150, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=150, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=150, null=True)),
                ('cloaking_enabled', models.BooleanField(default=False)),
                ('cloaked_title', models.CharField(blank=True, max_length=200, null=True)),
                ('cloaked_meta_description', models.TextField(blank=True, null=True)),
                ('cloaked_favicon', models.ImageField(blank=True, null=True, upload_to='dynamic_qr_favicons/')),
                ('cloaked_og_image', models.ImageField(blank=True, null=True, upload_to='dynamic_qr_og_images/')),
                ('cloaked_custom_js', models.TextField(blank=True, help_text='Restricted to Pro/Business. Executed in iframe wrapper context.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dynamic QR Code',
                'verbose_name_plural': 'Dynamic QR Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(blank=True, help_text='Mobile, Tablet, Desktop', max_length=50, null=True)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('country_code', models.CharField(default='XX', max_length=10)),
                ('region', models.CharField(default='Unknown', max_length=100)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_source', models.CharField(default='unknown', max_length=20)),
                ('gps_permission', models.CharField(default='not_required', max_length=20)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('gps_accuracy', models.FloatField(blank=True, null=True)),
                ('gps_captured_at', models.DateTimeField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, help_text='HTTP Referrer', max_length=500, null=True)),
                ('is_bot', models.BooleanField(default=False, help_text='Whether this scan/click was made by a bot')),
                ('is_qr_scan', models.BooleanField(default=False, help_text='True if originated from a QR code scan')),
                ('source', models.CharField(default='Direct', help_text='Traffic source (QR, Direct, Referral, etc.)', max_length=50)),
                ('visitor_id', models.CharField(blank=True, help_text='Hashed IP+UA for unique visitor tracking', max_length=64, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=150, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=150, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=150, null=True)),
                ('incoming_utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('incoming_utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('incoming_utm_campaign', models.CharField(blank=True, max_length=150, null=True)),
                ('incoming_utm_term', models.CharField(blank=True, max_length=150, null=True)),
                ('incoming_utm_content', models.CharField(blank=True, max_length=150, null=True)),
                ('was_cloaked', models.BooleanField(default=False)),
                ('redirect_result', models.CharField(choices=[('redirect_success', 'Successful Redirect'), ('password_required', 'Password Challenge'), ('password_failed', 'Password Failure'), ('expired', 'Expired Link Attempt'), ('disabled', 'Disabled Link Attempt'), ('gps_required', 'GPS Permission Required'), ('gps_denied', 'GPS Permission Denied'), ('invalid_link', 'Invalid Link Request'), ('bot_request', 'Bot Request Ignored')], db_index=True, default='redirect_success', max_length=30)),
                ('http_status', models.IntegerField(default=200)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='dynamic_qr.dynamicqrcode')),
            ],
            options={
                'verbose_name': 'QR Analytics',
                'verbose_name_plural': 'QR Analytics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
