# Generated by Django 4.2.30 on 2026-04-16 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamic_qr.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "OTP Verification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DynamicQRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        db_index=True,
                        default=dynamic_qr.models.generate_short_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "qr_name",
                    models.CharField(
                        help_text="A friendly name for this QR code", max_length=200
                    ),
                ),
                (
                    "qr_type",
                    models.CharField(
                        choices=[
                            ("url", "URL"),
                            ("text", "Text"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("sms", "SMS"),
                            ("wifi", "WiFi"),
                            ("vcard", "vCard"),
                            ("location", "Location"),
                        ],
                        default="url",
                        max_length=30,
                    ),
                ),
                (
                    "destination_url",
                    models.URLField(
                        blank=True,
                        help_text="Primary URL for direct redirect types",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "qr_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data for non-URL QR types",
                    ),
                ),
                ("fg_color", models.CharField(default="#000000", max_length=10)),
                ("bg_color", models.CharField(default="#ffffff", max_length=10)),
                ("body_style", models.CharField(default="square", max_length=20)),
                ("eye_style", models.CharField(default="square", max_length=20)),
                ("ball_style", models.CharField(default="square", max_length=20)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="dynamic_qr_logos/"
                    ),
                ),
                ("scan_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_qr_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic QR Code",
                "verbose_name_plural": "Dynamic QR Codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
