# Generated by Django 4.2.30 on 2026-04-16 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamic_qr.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicQRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        db_index=True,
                        default=dynamic_qr.models.generate_short_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "qr_name",
                    models.CharField(
                        help_text="A friendly name for this QR code", max_length=200
                    ),
                ),
                (
                    "qr_type",
                    models.CharField(
                        choices=[
                            ("url", "URL / Link"),
                            ("text", "Text Content"),
                            ("wifi", "Wi-Fi Network"),
                            ("location", "Map / Location"),
                            ("whatsapp", "WhatsApp"),
                            ("youtube", "YouTube"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("telegram", "Telegram"),
                            ("tiktok", "TikTok"),
                            ("x-twitter", "X / Twitter"),
                            ("snapchat", "Snapchat"),
                            ("pinterest", "Pinterest"),
                            ("linkedin", "LinkedIn"),
                            ("pdf", "PDF Document"),
                            ("audio", "Audio / MP3"),
                            ("video", "Video / MP4"),
                            ("image", "Image / Photo"),
                            ("pptx", "PowerPoint (PPTX)"),
                            ("excel", "Excel (XLSX)"),
                            ("word", "Word (DOCX)"),
                            ("email", "Email Address"),
                            ("phone", "Phone Call"),
                            ("sms", "SMS Message"),
                            ("vcard", "vCard (Contact)"),
                            ("calendar", "Calendar Event"),
                            ("booking", "Booking / Appt"),
                            ("google-review", "Google Review"),
                            ("google-forms", "Google Forms"),
                            ("google-doc", "Google Doc"),
                            ("google-sheets", "Google Sheets"),
                            ("play-market", "Play Market"),
                            ("app-store", "App Store"),
                            ("paypal", "PayPal"),
                            ("etsy", "Etsy Shop"),
                            ("amazon", "Amazon Product"),
                            ("venmo", "Venmo"),
                            ("upi", "UPI Payment"),
                            ("crypto", "Crypto Payment"),
                            ("spotify", "Spotify"),
                            ("link-list", "List of Links"),
                            ("custom-url", "Custom Short URL"),
                            ("office-365", "Office 365"),
                            ("2d-barcode", "2D Barcode"),
                        ],
                        default="url",
                        max_length=40,
                    ),
                ),
                (
                    "destination_url",
                    models.URLField(
                        blank=True,
                        help_text="Primary URL for direct redirect types",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "qr_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data for non-URL QR types",
                    ),
                ),
                (
                    "file_content",
                    models.FileField(
                        blank=True,
                        help_text="File associated with PDF, Audio, Video, etc.",
                        null=True,
                        upload_to="dynamic_qr_contents/",
                    ),
                ),
                ("fg_color", models.CharField(default="#000000", max_length=10)),
                ("bg_color", models.CharField(default="#ffffff", max_length=10)),
                ("body_style", models.CharField(default="square", max_length=20)),
                ("eye_style", models.CharField(default="square", max_length=20)),
                ("ball_style", models.CharField(default="square", max_length=20)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="dynamic_qr_logos/"
                    ),
                ),
                ("scan_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_qr_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic QR Code",
                "verbose_name_plural": "Dynamic QR Codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "OTP Verification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QRAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("browser", models.CharField(blank=True, max_length=50, null=True)),
                ("os", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="Mobile, Tablet, Desktop",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("country", models.CharField(default="Unknown", max_length=100)),
                ("city", models.CharField(default="Unknown", max_length=100)),
                (
                    "qr_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="dynamic_qr.dynamicqrcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Analytics",
                "verbose_name_plural": "QR Analytics",
                "ordering": ["-timestamp"],
            },
        ),
    ]
