# Generated by Django 5.2.17 on 2026-08-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_qr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicqrcode",
            name="custom_alias",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Custom URL alias",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="dynamicqrcode",
            name="domain",
            field=models.CharField(
                default="default",
                help_text="Domain used for the short URL",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="dynamicqrcode",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True, help_text="When the link expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="dynamicqrcode",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Hashed password for protected links",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dynamicqrcode",
            name="require_gps",
            field=models.BooleanField(
                default=False, help_text="Require GPS location to access"
            ),
        ),
        migrations.AddField(
            model_name="qranalytics",
            name="is_bot",
            field=models.BooleanField(
                default=False, help_text="Whether this scan/click was made by a bot"
            ),
        ),
        migrations.AddField(
            model_name="qranalytics",
            name="referrer",
            field=models.CharField(
                blank=True, help_text="HTTP Referrer", max_length=500, null=True
            ),
        ),
    ]
