# Generated by Django 4.2.30 on 2026-04-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_qr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicqrcode",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="dynamic_qr_logos/"
            ),
        ),
    ]
