# Generated by Django 5.2.17 on 2026-09-11

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicqrcode',
            name='branding_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_qr_branding/backgrounds/'),
        ),
        migrations.AddField(
            model_name='dynamicqrcode',
            name='branding_foreground_image',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_qr_branding/foregrounds/'),
        ),
    ]
