# Generated by Django 5.2.13 on 2026-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_qr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicqrcode",
            name="design_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Advanced design options like frames, text, error correction, etc.",
            ),
        ),
    ]
