# Generated by Django manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_qr', '0002_branding_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='qranalytics',
            name='detected_source',
            field=models.CharField(default='Direct / Unknown', help_text='Detected referring platform (e.g. Facebook)', max_length=100),
        ),
        migrations.AddField(
            model_name='qranalytics',
            name='detected_medium',
            field=models.CharField(blank=True, help_text='Detected referring medium (e.g. social)', max_length=100, null=True),
        ),
    ]
