# Generated by Django 5.2.17 on 2026-08-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_qr", "0002_dynamicqrcode_custom_alias_dynamicqrcode_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicqrcode",
            name="header_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom header configuration (text, color, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="dynamicqrcode",
            name="header_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show a custom header banner on the redirect page",
            ),
        ),
        migrations.AddField(
            model_name="dynamicqrcode",
            name="qr_enabled",
            field=models.BooleanField(
                default=False, help_text="Generate a QR code linking to this short URL"
            ),
        ),
    ]
