# Generated by Django 5.2.13 on 2026-04-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_qr", "0002_dynamicqrcode_design_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="qranalytics",
            name="country_code",
            field=models.CharField(default="XX", max_length=10),
        ),
        migrations.AddField(
            model_name="qranalytics",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qranalytics",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qranalytics",
            name="region",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
