# Generated by Django 5.2.17 on 2026-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_qr", "0003_dynamicqrcode_header_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qranalytics",
            name="is_qr_scan",
            field=models.BooleanField(
                default=False, help_text="True if originated from a QR code scan"
            ),
        ),
        migrations.AddField(
            model_name="qranalytics",
            name="source",
            field=models.CharField(
                default="Direct",
                help_text="Traffic source (QR, Direct, Referral, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="qranalytics",
            name="visitor_id",
            field=models.CharField(
                blank=True,
                help_text="Hashed IP+UA for unique visitor tracking",
                max_length=64,
                null=True,
            ),
        ),
    ]
