# Generated by Django with manual edits for Phase H

from django.db import migrations, models
import django.db.models.deletion

def check_and_seed_identifiers(apps, schema_editor):
    DynamicQRCode = apps.get_model('dynamic_qr', 'DynamicQRCode')
    ShortURLIdentifier = apps.get_model('dynamic_qr', 'ShortURLIdentifier')

    all_qrs = DynamicQRCode.objects.all()
    seen_identifiers = {}
    identifiers_to_create = []

    # Detect Collisions Before DB constraints throw
    for qr in all_qrs:
        if qr.short_code:
            # Same-row check
            if qr.short_code == qr.custom_alias:
                raise Exception(
                    f"Same-row collision detected! QR ID {qr.id} has short_code == custom_alias "
                    f"('{qr.short_code}'). Please remediate manually before migrating."
                )

            if qr.short_code in seen_identifiers:
                conflict_qr = seen_identifiers[qr.short_code]
                raise Exception(
                    f"Cross-row namespace collision detected on generated code '{qr.short_code}'! "
                    f"Conflicts between QR {conflict_qr.id} and QR {qr.id}."
                )
            seen_identifiers[qr.short_code] = qr
            identifiers_to_create.append(
                ShortURLIdentifier(value=qr.short_code, qr=qr, kind='generated')
            )

        if qr.custom_alias:
            if qr.custom_alias in seen_identifiers:
                conflict_qr = seen_identifiers[qr.custom_alias]
                raise Exception(
                    f"Cross-row namespace collision detected on alias '{qr.custom_alias}'! "
                    f"Conflicts between QR {conflict_qr.id} and QR {qr.id}."
                )
            seen_identifiers[qr.custom_alias] = qr
            identifiers_to_create.append(
                ShortURLIdentifier(value=qr.custom_alias, qr=qr, kind='alias')
            )

    # If we reached here, there are no collisions. Safely bulk create.
    ShortURLIdentifier.objects.bulk_create(identifiers_to_create)


def reverse_seed(apps, schema_editor):
    ShortURLIdentifier = apps.get_model('dynamic_qr', 'ShortURLIdentifier')
    # Safe to just wipe the registry because legacy columns remain intact during Phase H
    ShortURLIdentifier.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_qr', '0003_qranalytics_detected_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURLIdentifier',
            fields=[
                ('value', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('generated', 'Generated Short Code'), ('alias', 'Custom Alias')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='dynamic_qr.dynamicqrcode')),
            ],
            options={
                'unique_together': {('qr', 'kind')},
            },
        ),
        migrations.RunPython(check_and_seed_identifiers, reverse_seed),
    ]
