# Generated by Django 5.2.16 on 2026-07-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_qr', '0004_usersubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
