# Generated by Django 5.2.17 on 2026-09-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_qr', '0004_qranalytics_is_qr_scan_qranalytics_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicqrcode',
            name='header_data',
        ),
        migrations.RemoveField(
            model_name='dynamicqrcode',
            name='header_enabled',
        ),
        migrations.AddField(
            model_name='dynamicqrcode',
            name='header',
            field=models.CharField(blank=True, help_text='Custom URL path segment before the short code', max_length=20, null=True),
        ),
    ]
