# Generated by Django 5.2.17 on 2026-09-02 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video', models.FileField(upload_to='hero_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v'])])),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the playlist.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this video from the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Video',
                'verbose_name_plural': 'Hero Videos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
