# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herovideo',
            name='section',
            field=models.CharField(choices=[('short_url', 'Short URL Hero'), ('qr_code', 'QR Code Hero')], default='short_url', help_text='Select where this video should be displayed.', max_length=20),
        ),
    ]
