"""Helper to provide eight information cards for each media tool.
Each tool slug maps to a list of eight dictionaries with keys:
    icon (HTML/SVG), title, description.
"""

def _make_svg(path_d: str, fill="none", stroke="currentColor", stroke_width="2") -> str:
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" '
        f'fill="{fill}" stroke="{stroke}" stroke-width="{stroke_width}" stroke-linecap="round" '
        f'stroke-linejoin="round">{path_d}</svg>'
    )

ICONS = {
    "scissors": _make_svg('<circle cx="6" cy="6" r="3"></circle><circle cx="6" cy="18" r="3"></circle><line x1="20" y1="4" x2="8.12" y2="15.88"></line><line x1="14.47" y1="14.48" x2="20" y2="20"></line><line x1="8.12" y1="8.12" x2="12" y2="12"></line>'),
    "combine": _make_svg('<rect x="2" y="2" width="8" height="8" rx="2"></rect><rect x="14" y="2" width="8" height="8" rx="2"></rect><rect x="8" y="14" width="8" height="8" rx="2"></rect>'),
    "crop": _make_svg('<path d="M6.13 1 6 16a2 2 0 0 0 2 2h15"></path><path d="M1 6.13 16 6a2 2 0 0 1 2 2v15"></path>'),
    "resize": _make_svg('<polyline points="15 3 21 3 21 9"></polyline><polyline points="9 21 3 21 3 15"></polyline><line x1="21" y1="3" x2="14" y2="10"></line><line x1="3" y1="21" x2="10" y2="14"></line>'),
    "rotate": _make_svg('<path d="M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.57-8.38l5.67-5.67"></path>'),
    "flip": _make_svg('<polyline points="8 3 4 7 8 11"></polyline><path d="M4 7h16"></path><polyline points="16 21 20 17 16 13"></polyline><path d="M20 17H4"></path>'),
    "speed": _make_svg('<circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline>'),
    "compress": _make_svg('<polyline points="4 14 10 14 10 20"></polyline><polyline points="20 10 14 10 14 4"></polyline><line x1="14" y1="10" x2="21" y2="3"></line><line x1="3" y1="21" x2="10" y2="14"></line>'),
    "convert": _make_svg('<polyline points="17 1 21 5 17 9"></polyline><path d="M3 11V9a4 4 0 0 1 4-4h14"></path><polyline points="7 23 3 19 7 15"></polyline><path d="M21 13v2a4 4 0 0 1-4 4H3"></path>'),
    "gif": _make_svg('<rect x="2" y="3" width="20" height="14" rx="2"></rect><line x1="8" y1="21" x2="16" y2="21"></line><line x1="12" y1="17" x2="12" y2="21"></line>'),
    "volume_x": _make_svg('<polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><line x1="23" y1="9" x2="17" y2="15"></line><line x1="17" y1="9" x2="23" y2="15"></line>'),
    "music": _make_svg('<path d="M9 18V5l12-2v13"></path><circle cx="6" cy="18" r="3"></circle><circle cx="18" cy="16" r="3"></circle>'),
    "volume_2": _make_svg('<polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><path d="M19.07 4.93a10 10 0 0 1 0 14.14M15.54 8.46a5 5 0 0 1 0 7.07"></path>'),
    "rewind": _make_svg('<polygon points="11 19 2 12 11 5 11 19"></polygon><polygon points="22 19 13 12 22 5 22 19"></polygon>'),
    "sliders": _make_svg('<line x1="4" y1="21" x2="4" y2="14"></line><line x1="4" y1="10" x2="4" y2="3"></line><line x1="12" y1="21" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="3"></line><line x1="20" y1="21" x2="20" y2="16"></line><line x1="20" y1="12" x2="20" y2="3"></line><line x1="1" y1="14" x2="7" y2="14"></line><line x1="9" y1="8" x2="15" y2="8"></line><line x1="17" y1="16" x2="23" y2="16"></line>'),
    "video": _make_svg('<polygon points="23 7 16 12 23 17 23 7"></polygon><rect x="1" y="5" width="15" height="14" rx="2" ry="2"></rect>'),
    "camera": _make_svg('<path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle>'),
    "shield": _make_svg('<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>'),
    "zap": _make_svg('<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon>'),
    "sparkles": _make_svg('<path d="m12 3-1.9 5.8a2 2 0 0 1-1.3 1.3L3 12l5.8 1.9a2 2 0 0 1 1.3 1.3L12 21l1.9-5.8a2 2 0 0 1 1.3-1.3L21 12l-5.8-1.9a2 2 0 0 1-1.3-1.3Z"></path>'),
    "check": _make_svg('<polyline points="20 6 9 17 4 12"></polyline>'),
    "download": _make_svg('<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line>'),
    "lock": _make_svg('<rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path>'),
    "layers": _make_svg('<polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline>'),
}


def _default_cards(title: str, verb: str):
    return [
        {"icon": ICONS["zap"], "title": f"Instant {title}", "description": f"Fast and accurate {verb} processing directly in your browser."},
        {"icon": ICONS["layers"], "title": "Lossless Quality", "description": "Retains original video clarity with zero compression artifacts."},
        {"icon": ICONS["sliders"], "title": "Full Customization", "description": f"Fine-tune every parameter to fit your exact video requirements."},
        {"icon": ICONS["video"], "title": "Real-Time Preview", "description": "Interactive visual canvas to preview changes before processing."},
        {"icon": ICONS["shield"], "title": "Privacy Guaranteed", "description": "Encrypted processing with automatic temporary file cleanup."},
        {"icon": ICONS["convert"], "title": "Multiple Formats", "description": "Export cleanly to MP4, MOV, WEBM, MKV, and GIF formats."},
        {"icon": ICONS["download"], "title": "High-Speed Download", "description": "Download processed videos at maximum server bandwidth."},
        {"icon": ICONS["check"], "title": "No Watermarks", "description": "100% free with no forced branding or watermark overlays."},
    ]


CARDS_DATA = {
    "crop": [
        {"icon": ICONS["crop"], "title": "Visual Crop Box", "description": "Drag and resize the interactive crop box freely over your video."},
        {"icon": ICONS["layers"], "title": "Social Presets", "description": "16:9 Landscape, 9:16 Shorts/Reels, 1:1 Square, and 4:5 Portrait."},
        {"icon": ICONS["sliders"], "title": "Pixel-Perfect Positioning", "description": "Explicit X, Y, Width, and Height controls down to the single pixel."},
        {"icon": ICONS["video"], "title": "Synchronized Preview", "description": "Canvas renders your selected crop region with live video playback."},
        {"icon": ICONS["shield"], "title": "Zero Quality Loss", "description": "High-fidelity FFmpeg crop filters preserve crisp image sharpness."},
        {"icon": ICONS["convert"], "title": "Universal Compatibility", "description": "Export your cropped video in MP4, MOV, WEBM, or MKV format."},
        {"icon": ICONS["download"], "title": "Instant Export", "description": "Fast video processing with direct one-click download."},
        {"icon": ICONS["check"], "title": "Watermark Free", "description": "Completely free with no branding, banners, or watermarks added."},
    ],
    "trim": [
        {"icon": ICONS["scissors"], "title": "Precision Scrubbing", "description": "Set start and end timestamps down to 1/10th of a second."},
        {"icon": ICONS["sliders"], "title": "Interactive Timeline", "description": "Drag dual-handle timeline markers visually over the playbar."},
        {"icon": ICONS["zap"], "title": "Lossless Stream Copy", "description": "Instant fast trimming without unnecessary re-encoding."},
        {"icon": ICONS["video"], "title": "Playback Looping", "description": "Loop through the exact selected duration to verify cut accuracy."},
        {"icon": ICONS["shield"], "title": "Private & Secure", "description": "Your private clips are automatically purged after download."},
        {"icon": ICONS["convert"], "title": "Flexible Output Formats", "description": "Save clips directly as MP4, MOV, WEBM, or MKV files."},
        {"icon": ICONS["download"], "title": "Lightning Fast", "description": "Download trimmed clips in seconds with dedicated render pipelines."},
        {"icon": ICONS["check"], "title": "Original Bitrate Kept", "description": "Audio and video streams maintain full pristine resolution."},
    ],
    "merge": [
        {"icon": ICONS["combine"], "title": "Multi-Clip Stitching", "description": "Combine 2 or more video clips seamlessly into a single file."},
        {"icon": ICONS["layers"], "title": "Auto Resolution Sync", "description": "Automatically reconciles differing aspect ratios and frame rates."},
        {"icon": ICONS["sliders"], "title": "Drag & Drop Ordering", "description": "Upload multiple clips easily and process them in perfect sequence."},
        {"icon": ICONS["music"], "title": "Clean Audio Concat", "description": "Harmonizes audio sample rates for smooth transition between clips."},
        {"icon": ICONS["shield"], "title": "Encrypted Uploads", "description": "Secure file handling with automatic storage cleanup."},
        {"icon": ICONS["convert"], "title": "Universal MP4 Output", "description": "Creates standard H.264 video playable on any device or platform."},
        {"icon": ICONS["download"], "title": "One-Click Download", "description": "Download the merged compilation file instantly."},
        {"icon": ICONS["check"], "title": "No Length Limits", "description": "Merge both short social clips and long continuous recordings."},
    ],
    "resize": [
        {"icon": ICONS["resize"], "title": "Resolution Presets", "description": "Quickly choose 4K, 1080p Full HD, 720p HD, 480p, or custom dimensions."},
        {"icon": ICONS["layers"], "title": "Aspect Ratio Lock", "description": "Maintain exact proportions to prevent stretching or distortion."},
        {"icon": ICONS["sliders"], "title": "Letterbox & Pad Modes", "description": "Fit, fill, or pad videos with custom solid background colors."},
        {"icon": ICONS["video"], "title": "Visual Zoom & Pan", "description": "Center, zoom, and frame videos accurately for any screen."},
        {"icon": ICONS["shield"], "title": "Lossless Resampling", "description": "High quality bicubic/lanczos scaling for razor sharp visuals."},
        {"icon": ICONS["convert"], "title": "Format Flexibility", "description": "Export in MP4, MOV, WEBM, or MKV containers seamlessly."},
        {"icon": ICONS["download"], "title": "Rapid Encoding", "description": "Optimized GPU/CPU encoding pipelines for swift delivery."},
        {"icon": ICONS["check"], "title": "Clean Video Stream", "description": "No watermarks, no ads, and no quality degradation."},
    ],
    "rotate": [
        {"icon": ICONS["rotate"], "title": "90° / 180° / 270° Rotation", "description": "Fix sideways or upside-down smartphone video recordings."},
        {"icon": ICONS["flip"], "title": "Free Angle Flip", "description": "Combine rotation with vertical or horizontal orientation fixes."},
        {"icon": ICONS["video"], "title": "Live Orientation Preview", "description": "Preview rotated canvas view instantly in your browser."},
        {"icon": ICONS["zap"], "title": "Lossless Metadata Rotation", "description": "Fast rotation matrix transformations for rapid turnaround."},
        {"icon": ICONS["shield"], "title": "Secure Cloud Processing", "description": "Your files remain strictly confidential and self-destruct."},
        {"icon": ICONS["convert"], "title": "Universal Export", "description": "Compatible with iPhone, Android, YouTube, and TikTok playback."},
        {"icon": ICONS["download"], "title": "Immediate Download", "description": "Grab the corrected orientation video with a single click."},
        {"icon": ICONS["check"], "title": "Zero Watermark", "description": "Pristine video without any branding or watermark overlays."},
    ],
    "flip": [
        {"icon": ICONS["flip"], "title": "Horizontal Mirroring", "description": "Flip selfie videos and webcam streams horizontally."},
        {"icon": ICONS["rotate"], "title": "Vertical Inversion", "description": "Invert upside-down drone or camera footage effortlessly."},
        {"icon": ICONS["video"], "title": "Instant Mirror Preview", "description": "Check mirrored motion live on the playback canvas."},
        {"icon": ICONS["zap"], "title": "Fast FFmpeg Filter", "description": "High-efficiency hflip and vflip transformations."},
        {"icon": ICONS["shield"], "title": "Privacy Shield", "description": "Temporary files automatically deleted after conversion."},
        {"icon": ICONS["convert"], "title": "MP4 / MOV / WEBM", "description": "Select the ideal output container for your target audience."},
        {"icon": ICONS["download"], "title": "High-Speed Render", "description": "Processed video is ready for download in just moments."},
        {"icon": ICONS["check"], "title": "Full Audio Retention", "description": "Audio remains in pristine stereo synchronization."},
    ],
    "speed": [
        {"icon": ICONS["speed"], "title": "Smooth Slow Motion", "description": "Slow down action clips to 0.25x, 0.5x, or 0.75x with fluid motion."},
        {"icon": ICONS["zap"], "title": "Hyperlapse & Speed Up", "description": "Accelerate videos up to 2x, 4x, 8x, or 16x for time-lapses."},
        {"icon": ICONS["music"], "title": "Pitch-Corrected Audio", "description": "Atempo audio filter maintains natural pitch during speed shifts."},
        {"icon": ICONS["video"], "title": "Live Speed Preview", "description": "Preview accelerated or slow motion directly in the web player."},
        {"icon": ICONS["shield"], "title": "Encrypted Processing", "description": "Processed safely on dedicated high-performance servers."},
        {"icon": ICONS["convert"], "title": "Cross-Platform Video", "description": "Export cleanly to MP4, MOV, WEBM, or MKV containers."},
        {"icon": ICONS["download"], "title": "Direct File Download", "description": "Download your accelerated or slow-motion video immediately."},
        {"icon": ICONS["check"], "title": "Frame Blending", "description": "Smooth frame interpolation for cinematic visual results."},
    ],
    "compress": [
        {"icon": ICONS["compress"], "title": "Up to 85% Size Reduction", "description": "Shrink massive video files for email, Discord, or web upload."},
        {"icon": ICONS["sliders"], "title": "Smart Compression Modes", "description": "Choose between Low, Medium, High, or Custom CRF levels."},
        {"icon": ICONS["layers"], "title": "Perceptual Clarity", "description": "Advanced H.264/H.265 compression preserves sharp details."},
        {"icon": ICONS["video"], "title": "File Size Estimator", "description": "Target exact megabyte thresholds easily."},
        {"icon": ICONS["shield"], "title": "Private & Secure", "description": "Automated server cleanup protects sensitive content."},
        {"icon": ICONS["convert"], "title": "Web Optimized (MP4)", "description": "Fast start metadata flag enabled for instant web playback."},
        {"icon": ICONS["download"], "title": "Instant Download", "description": "Grab the ultra-compact video file right away."},
        {"icon": ICONS["check"], "title": "No Watermarks", "description": "100% clean compression without logos or stamps."},
    ],
    "convert": [
        {"icon": ICONS["convert"], "title": "Universal Converter", "description": "Convert between MP4, MOV, AVI, MKV, WEBM, FLV, and WMV."},
        {"icon": ICONS["layers"], "title": "Modern Codecs", "description": "Outputs encoded in H.264, HEVC/H.265, VP9, or AV1."},
        {"icon": ICONS["music"], "title": "Audio Transcoding", "description": "Converts AAC, MP3, Opus, or AC3 streams seamlessly."},
        {"icon": ICONS["video"], "title": "High Quality Profile", "description": "Optimal bitrates selected automatically for the highest quality."},
        {"icon": ICONS["shield"], "title": "Private Cloud", "description": "No logs, no trackers, and automatic file destruction."},
        {"icon": ICONS["download"], "title": "Blazing Transcode", "description": "Multi-threaded encoding delivers fast conversion."},
        {"icon": ICONS["zap"], "title": "Device Presets", "description": "Ready for iPhone, iPad, Android, Windows, Mac, and TVs."},
        {"icon": ICONS["check"], "title": "Lossless Audio/Video", "description": "Retains original resolution, color space, and metadata."},
    ],
    "video-to-gif": [
        {"icon": ICONS["gif"], "title": "High Quality Color Palette", "description": "Generates custom 256-color palette to eliminate color banding."},
        {"icon": ICONS["sliders"], "title": "FPS & Width Controls", "description": "Set frame rate (10-30 fps) and width for optimal file size."},
        {"icon": ICONS["video"], "title": "Seamless Loop", "description": "Creates perfectly repeating animated GIFs for memes and chat."},
        {"icon": ICONS["zap"], "title": "Bayer Dithering", "description": "Smooth gradients and transitions with smart dithering algorithms."},
        {"icon": ICONS["shield"], "title": "Private Processing", "description": "Safe upload and automatic cleanup after conversion."},
        {"icon": ICONS["download"], "title": "One-Click GIF Download", "description": "Save animated GIF directly to your computer or phone."},
        {"icon": ICONS["check"], "title": "Discord & Slack Ready", "description": "Optimized lightweight GIF files for emojis and reactions."},
        {"icon": ICONS["sparkles"], "title": "Crisp Animation", "description": "Vibrant visual clarity compared to standard GIF converters."},
    ],
    "gif-to-video": [
        {"icon": ICONS["video"], "title": "GIF to MP4 / WEBM", "description": "Convert bulky GIF animations into lightweight smooth videos."},
        {"icon": ICONS["compress"], "title": "90% File Size Savings", "description": "Modern MP4 video formats use a fraction of GIF bandwidth."},
        {"icon": ICONS["layers"], "title": "Even Dimension Padding", "description": "Automatically pads dimensions to even numbers for H.264 compatibility."},
        {"icon": ICONS["speed"], "title": "Smooth 60 FPS Playback", "description": "Enjoy stutter-free hardware accelerated video playback."},
        {"icon": ICONS["shield"], "title": "Secure Conversion", "description": "Temporary files automatically deleted after processing."},
        {"icon": ICONS["convert"], "title": "Cross-Platform Video", "description": "Playable across all modern mobile browsers and social networks."},
        {"icon": ICONS["download"], "title": "Fast Download", "description": "Get the converted video file in just seconds."},
        {"icon": ICONS["check"], "title": "Zero Artifacts", "description": "Clean up GIF color quantization artifacts during encoding."},
    ],
    "remove-audio": [
        {"icon": ICONS["volume_x"], "title": "Mute Video Completely", "description": "Strip all audio tracks, microphones, and background noise."},
        {"icon": ICONS["zap"], "title": "Lossless Stream Copy", "description": "Removes audio without touching or re-encoding video pixels."},
        {"icon": ICONS["video"], "title": "Instant Preview", "description": "Verify that all soundtrack channels are silenced in the player."},
        {"icon": ICONS["compress"], "title": "Reduced File Size", "description": "Trimming unused audio tracks reduces final video file size."},
        {"icon": ICONS["shield"], "title": "Confidential & Safe", "description": "Protects private background conversations by silencing audio."},
        {"icon": ICONS["convert"], "title": "Select Output Container", "description": "Export as MP4, MOV, WEBM, or MKV effortlessly."},
        {"icon": ICONS["download"], "title": "Instant Download", "description": "Completed silent video available immediately."},
        {"icon": ICONS["check"], "title": "No Watermarks", "description": "Completely free tool with clean, unbranded video export."},
    ],
    "extract-audio": [
        {"icon": ICONS["music"], "title": "Extract MP3 / WAV / AAC", "description": "Extract crystal-clear audio tracks and music from video clips."},
        {"icon": ICONS["sliders"], "title": "Bitrate Selection", "description": "Choose between 128k, 192k, 256k, and 320k high fidelity bitrates."},
        {"icon": ICONS["zap"], "title": "Direct Stream Demuxing", "description": "Lossless stream extraction for original studio quality."},
        {"icon": ICONS["layers"], "title": "Multi-Format Support", "description": "Extract to MP3, WAV, AAC, M4A, FLAC, or OGG."},
        {"icon": ICONS["shield"], "title": "Private Processing", "description": "Automatic file purging after download for total privacy."},
        {"icon": ICONS["video"], "title": "Soundtrack Preservation", "description": "Keeps full dynamic range and stereo separation."},
        {"icon": ICONS["download"], "title": "Fast Audio Download", "description": "Download your audio soundtrack file in seconds."},
        {"icon": ICONS["check"], "title": "Podcast & Music Ready", "description": "Perfect for podcast recording, music extraction, and voiceovers."},
    ],
    "change-volume": [
        {"icon": ICONS["volume_2"], "title": "Boost Volume Up to 400%", "description": "Amplify quiet voices and low-volume video recordings."},
        {"icon": ICONS["sliders"], "title": "Attenuate Loud Audio", "description": "Reduce harsh or clipped audio down to comfortable levels."},
        {"icon": ICONS["music"], "title": "Anti-Distortion Limiter", "description": "Prevents harsh audio clipping and digital crackle."},
        {"icon": ICONS["video"], "title": "Synchronized Preview", "description": "Listen to the adjusted volume curve in real-time."},
        {"icon": ICONS["shield"], "title": "Privacy First", "description": "Temporary media files are securely deleted after processing."},
        {"icon": ICONS["convert"], "title": "Multiple Output Formats", "description": "Save in MP4, MOV, WEBM, or MKV format."},
        {"icon": ICONS["download"], "title": "Fast Export", "description": "Quick audio re-encoding and immediate download."},
        {"icon": ICONS["check"], "title": "Pure Audio Quality", "description": "Preserves original video frames without re-compression."},
    ],
    "add-audio": [
        {"icon": ICONS["music"], "title": "Mix or Replace Audio", "description": "Overlay background music or replace original dialogue cleanly."},
        {"icon": ICONS["sliders"], "title": "Independent Volume Controls", "description": "Balance original video audio vs. new music track volume."},
        {"icon": ICONS["layers"], "title": "Audio Duration Matching", "description": "Automatically loops or trims audio track to match video length."},
        {"icon": ICONS["video"], "title": "Dual Stream Preview", "description": "Preview the mixed soundtrack alongside video playback."},
        {"icon": ICONS["shield"], "title": "Encrypted Processing", "description": "Zero permanent storage of your uploaded music and videos."},
        {"icon": ICONS["convert"], "title": "Universal Video Format", "description": "Export in high-definition MP4 with stereo AAC audio."},
        {"icon": ICONS["download"], "title": "Fast Processing", "description": "Render and download your combined video in moments."},
        {"icon": ICONS["check"], "title": "No Watermarks", "description": "Unrestricted output with no added watermarks."},
    ],
    "add-text": [
        {"icon": ICONS["sparkles"], "title": "Custom Typography", "description": "Add titles, subtitles, watermarks, and captions easily."},
        {"icon": ICONS["sliders"], "title": "Font, Size & Color", "description": "Customize text color, background banner, and font styling."},
        {"icon": ICONS["layers"], "title": "Interactive Placement", "description": "Position text at top, center, bottom, or custom coordinates."},
        {"icon": ICONS["speed"], "title": "Time-Bound Overlays", "description": "Display text during specific timestamps or throughout the clip."},
        {"icon": ICONS["video"], "title": "Live Studio Preview", "description": "See text placement directly overlaid on the video canvas."},
        {"icon": ICONS["shield"], "title": "Secure Cloud", "description": "Private processing with automatic temporary file cleanup."},
        {"icon": ICONS["download"], "title": "Fast Export", "description": "Burn subtitles or titles directly into the video stream."},
        {"icon": ICONS["check"], "title": "High Contrast Box", "description": "Optional translucent background box for maximum readability."},
    ],
    "add-image": [
        {"icon": ICONS["camera"], "title": "Logo & Image Overlay", "description": "Brand your videos with PNG logos, stickers, and icons."},
        {"icon": ICONS["sliders"], "title": "Transparency & Scale", "description": "Adjust logo opacity (10-100%) and relative scale percentage."},
        {"icon": ICONS["layers"], "title": "Corner & Custom Anchors", "description": "Pin logos to top-left, top-right, bottom-right, or center."},
        {"icon": ICONS["speed"], "title": "Timing Controls", "description": "Set custom start and end display timestamps for the watermark."},
        {"icon": ICONS["video"], "title": "Real-Time Canvas Drag", "description": "Visually position the image overlay over the video preview."},
        {"icon": ICONS["shield"], "title": "Zero Data Retention", "description": "Uploaded logos and video clips are safely deleted after use."},
        {"icon": ICONS["download"], "title": "Quick Render", "description": "Fast FFmpeg overlay encoding for high-speed delivery."},
        {"icon": ICONS["check"], "title": "PNG Alpha Support", "description": "Preserves crystal-clear transparency for smooth logo blending."},
    ],
    "blur": [
        {"icon": ICONS["sparkles"], "title": "Area & Full Video Blur", "description": "Blur sensitive information, faces, license plates, or backgrounds."},
        {"icon": ICONS["sliders"], "title": "Adjustable Blur Strength", "description": "Dial blur intensity from subtle softness to heavy obscurity."},
        {"icon": ICONS["crop"], "title": "Interactive Blur Box", "description": "Drag the blur region directly over confidential information."},
        {"icon": ICONS["video"], "title": "Live Canvas Preview", "description": "Verify that sensitive details are fully protected before exporting."},
        {"icon": ICONS["shield"], "title": "Privacy & GDPR Compliant", "description": "Completely obscures confidential data permanently in pixels."},
        {"icon": ICONS["convert"], "title": "MP4 / MOV / WEBM Export", "description": "Export in high compatibility formats for secure sharing."},
        {"icon": ICONS["download"], "title": "Immediate Download", "description": "Fast video encoding with direct download link."},
        {"icon": ICONS["check"], "title": "No Watermarks", "description": "Free and clean video export with zero added branding."},
    ],
    "brighten": [
        {"icon": ICONS["sparkles"], "title": "Color & Light Correction", "description": "Brighten underexposed videos and restore dark scenes."},
        {"icon": ICONS["sliders"], "title": "Brightness, Contrast & Saturation", "description": "Fine-tune exposure, vividness, and tonal depth."},
        {"icon": ICONS["layers"], "title": "Gamma Correction", "description": "Adjust mid-tones without blowing out highlights."},
        {"icon": ICONS["video"], "title": "Real-Time Color Grade", "description": "See instant color grading changes in the video player."},
        {"icon": ICONS["shield"], "title": "Private Cloud Processing", "description": "Your videos are processed confidentially on secure servers."},
        {"icon": ICONS["convert"], "title": "Universal Compatibility", "description": "Export in MP4, MOV, WEBM, or MKV containers."},
        {"icon": ICONS["download"], "title": "Fast Export", "description": "Download the enhanced video clip right away."},
        {"icon": ICONS["check"], "title": "Clean Video Master", "description": "Full HD preservation with vibrant natural colors."},
    ],
    "split-screen": [
        {"icon": ICONS["combine"], "title": "Multi-Video Collage", "description": "Place 2, 3, or 4 videos side-by-side or in a 2x2 grid."},
        {"icon": ICONS["layers"], "title": "Side-by-Side & Stacked", "description": "Choose between horizontal, vertical, or grid split screen."},
        {"icon": ICONS["speed"], "title": "Synchronized Playback", "description": "All video panes start simultaneously for comparison."},
        {"icon": ICONS["music"], "title": "Audio Track Mixing", "description": "Blends or selects dominant audio stream cleanly."},
        {"icon": ICONS["shield"], "title": "Secure Uploads", "description": "Encrypted handling with automatic temporary file destruction."},
        {"icon": ICONS["convert"], "title": "High Definition MP4", "description": "Export in 1080p Full HD compatible with all devices."},
        {"icon": ICONS["download"], "title": "One-Click Download", "description": "Download the combined split-screen video instantly."},
        {"icon": ICONS["check"], "title": "Comparison & Reactions", "description": "Ideal for before/after comparisons and reaction videos."},
    ],
    "stabilize": [
        {"icon": ICONS["video"], "title": "Shaky Footage Stabilization", "description": "Smooth out handheld, walking, action-cam, and drone footage."},
        {"icon": ICONS["sliders"], "title": "Multi-Pass Motion Analysis", "description": "Calculates camera transform vectors using vid.stab technology."},
        {"icon": ICONS["layers"], "title": "Strength Presets", "description": "Choose between Light, Medium, or Heavy stabilization strength."},
        {"icon": ICONS["sparkles"], "title": "Adaptive Zoom & Crop", "description": "Eliminates black border artifacts during camera compensation."},
        {"icon": ICONS["shield"], "title": "Private & Secure", "description": "Automated server cleanup after video export."},
        {"icon": ICONS["convert"], "title": "Universal MP4 Output", "description": "Save in high-bitrate MP4 with pristine image quality."},
        {"icon": ICONS["download"], "title": "Fast Turnaround", "description": "Optimized multi-threaded motion smoothing pipeline."},
        {"icon": ICONS["check"], "title": "Cinematic Smoothness", "description": "Gives smartphone recordings professional gimbal smoothness."},
    ],
    "sync-audio": [
        {"icon": ICONS["speed"], "title": "Fix Out-of-Sync Audio", "description": "Shift audio forward or backward by milliseconds to fix lip sync."},
        {"icon": ICONS["sliders"], "title": "Fine Millisecond Tuning", "description": "Adjust audio offset precisely (+/- seconds or milliseconds)."},
        {"icon": ICONS["music"], "title": "Live Sync Check", "description": "Verify spoken dialogue and mouth movements in preview."},
        {"icon": ICONS["zap"], "title": "Lossless Audio Delay", "description": "Applies itsoffset or adelay without video re-compression."},
        {"icon": ICONS["shield"], "title": "Privacy Guaranteed", "description": "Temporary media files deleted automatically after download."},
        {"icon": ICONS["convert"], "title": "Universal Video Export", "description": "Export in MP4, MOV, WEBM, or MKV containers."},
        {"icon": ICONS["download"], "title": "Instant Export", "description": "Download your perfectly synchronized video immediately."},
        {"icon": ICONS["check"], "title": "No Watermarks", "description": "100% free with no branding or quality loss."},
    ],
    "transition": [
        {"icon": ICONS["sparkles"], "title": "Cinematic Fade Transitions", "description": "Apply smooth fade-in, fade-out, or crossfade transitions."},
        {"icon": ICONS["sliders"], "title": "Custom Duration & Color", "description": "Set fade duration (0.5s - 5s) and choose black or white fade."},
        {"icon": ICONS["music"], "title": "Audio Fade Included", "description": "Smooth afade audio curve prevents harsh volume pops."},
        {"icon": ICONS["video"], "title": "Studio Video Preview", "description": "Review intro and outro fade transitions in the player."},
        {"icon": ICONS["shield"], "title": "Secure Processing", "description": "All files strictly confidential and automatically purged."},
        {"icon": ICONS["convert"], "title": "Multi-Format Export", "description": "Save in MP4, MOV, WEBM, or MKV containers."},
        {"icon": ICONS["download"], "title": "Fast Encoding", "description": "Download the finished video with smooth transitions."},
        {"icon": ICONS["check"], "title": "Professional Finish", "description": "Gives raw recordings an elegant cinematic polish."},
    ],
    "repair": [
        {"icon": ICONS["shield"], "title": "Repair Corrupted Videos", "description": "Fix broken MOOV atoms, corrupted index headers, and truncated files."},
        {"icon": ICONS["zap"], "title": "Fast MOOV Atom Relocation", "description": "Move index headers to file beginning for instant web streaming."},
        {"icon": ICONS["layers"], "title": "Stream Rebuilding", "description": "Reconstruct keyframe indices and repair damaged audio/video packets."},
        {"icon": ICONS["video"], "title": "Playability Restoration", "description": "Make unplayable drone, phone, or dashcam videos playable again."},
        {"icon": ICONS["lock"], "title": "Safe File Recovery", "description": "Non-destructive processing preserves all recoverable media data."},
        {"icon": ICONS["convert"], "title": "Standard MP4 Re-mux", "description": "Outputs clean, universally compatible MP4 files."},
        {"icon": ICONS["download"], "title": "Direct File Download", "description": "Download your repaired video with full audio and video tracks."},
        {"icon": ICONS["check"], "title": "High Recovery Rate", "description": "Recovers footage from crashes, sudden shutdowns, and power loss."},
    ],
    "background": [
        {"icon": ICONS["layers"], "title": "Aspect Ratio Padding", "description": "Adapt landscape videos for 9:16 vertical TikTok/Reels without cropping."},
        {"icon": ICONS["sparkles"], "title": "Blurred Background", "description": "Fills side or top borders with an aesthetic blurred video reflection."},
        {"icon": ICONS["sliders"], "title": "Solid Color Framing", "description": "Fill empty border margins with custom solid colors (black, white, etc.)."},
        {"icon": ICONS["video"], "title": "Live Studio Preview", "description": "Preview your framed video inside the target aspect ratio."},
        {"icon": ICONS["shield"], "title": "Privacy Shield", "description": "Automated server cleanup protects your content."},
        {"icon": ICONS["convert"], "title": "Universal Formats", "description": "Export in high-resolution MP4 or MOV ready for social media."},
        {"icon": ICONS["download"], "title": "Fast Processing", "description": "Download the formatted video in seconds."},
        {"icon": ICONS["check"], "title": "No Watermarks", "description": "Clean, unbranded output for commercial or personal use."},
    ],
    "reverse": [
        {"icon": ICONS["rewind"], "title": "Reverse Video Playback", "description": "Play video clips backward from finish to start."},
        {"icon": ICONS["music"], "title": "Reverse Audio Track", "description": "Reverse accompanying audio stream or mute for silence."},
        {"icon": ICONS["video"], "title": "Instant Backward Preview", "description": "Preview reversed motion directly in the video player."},
        {"icon": ICONS["zap"], "title": "Frame-by-Frame Inversion", "description": "High accuracy reverse filter maintains original frame rates."},
        {"icon": ICONS["shield"], "title": "Safe Cloud Processing", "description": "Temporary media files deleted immediately after download."},
        {"icon": ICONS["convert"], "title": "Export Formats", "description": "Download in MP4, MOV, WEBM, or MKV format."},
        {"icon": ICONS["download"], "title": "Immediate Download", "description": "Fast video generation with direct download link."},
        {"icon": ICONS["check"], "title": "Creative Effects", "description": "Perfect for magic tricks, looping effects, and funny clips."},
    ],
    "fade": [
        {"icon": ICONS["sparkles"], "title": "Fade In & Fade Out", "description": "Add smooth intro fade-in and outro fade-out transitions."},
        {"icon": ICONS["sliders"], "title": "Custom Durations", "description": "Configure separate fade-in and fade-out durations in seconds."},
        {"icon": ICONS["layers"], "title": "Black or White Fade", "description": "Choose fade color to match your video's style and mood."},
        {"icon": ICONS["music"], "title": "Synchronized Audio Fade", "description": "Gradually increases intro volume and gently fades out the outro."},
        {"icon": ICONS["shield"], "title": "Secure & Private", "description": "Encrypted file handling with automatic storage cleanup."},
        {"icon": ICONS["convert"], "title": "Universal Video Output", "description": "Compatible with all media players and social networks."},
        {"icon": ICONS["download"], "title": "Quick Render", "description": "Get your polished video file in moments."},
        {"icon": ICONS["check"], "title": "No Watermarks", "description": "Completely free with zero forced overlays."},
    ],
    "effects": [
        {"icon": ICONS["sparkles"], "title": "Filters & Color Effects", "description": "Apply Grayscale, Sepia, Invert, Vintage, or custom color grades."},
        {"icon": ICONS["sliders"], "title": "Brightness & Contrast", "description": "Fine-tune brightness, contrast, and color saturation levels."},
        {"icon": ICONS["video"], "title": "Real-Time Filter Preview", "description": "See artistic filters rendered live on the video canvas."},
        {"icon": ICONS["layers"], "title": "Broadcast Quality", "description": "Color transformations executed using FFmpeg eq and curves filters."},
        {"icon": ICONS["shield"], "title": "Private Cloud", "description": "Your footage is kept confidential and deleted after use."},
        {"icon": ICONS["convert"], "title": "Multiple Formats", "description": "Export as MP4, MOV, WEBM, or MKV."},
        {"icon": ICONS["download"], "title": "Instant Download", "description": "Download your stylised video clip immediately."},
        {"icon": ICONS["check"], "title": "No Branding", "description": "Pristine visual export without unwanted logos."},
    ],
    "fps": [
        {"icon": ICONS["speed"], "title": "Change Video Frame Rate", "description": "Convert frame rates to 60 FPS, 30 FPS, 24 FPS (Cinematic), or 120 FPS."},
        {"icon": ICONS["layers"], "title": "Smooth Frame Interpolation", "description": "Interpolates or drops frames cleanly without stutter."},
        {"icon": ICONS["video"], "title": "Playback Compatibility", "description": "Standardize non-standard variable frame rate (VFR) videos to CFR."},
        {"icon": ICONS["music"], "title": "Audio Synchronization", "description": "Keeps audio perfectly in sync with the new frame cadence."},
        {"icon": ICONS["shield"], "title": "Encrypted Processing", "description": "Automatic file destruction after video export."},
        {"icon": ICONS["convert"], "title": "Universal Export", "description": "Export in MP4, MOV, WEBM, or MKV container."},
        {"icon": ICONS["download"], "title": "Fast Transcoding", "description": "Multi-threaded encoding for rapid output."},
        {"icon": ICONS["check"], "title": "Zero Quality Loss", "description": "Retains original pixel resolution and sharp image clarity."},
    ],
    "loop": [
        {"icon": ICONS["rotate"], "title": "Loop Video N Times", "description": "Repeat video clips 2x, 3x, 5x, 10x, or custom repeat counts."},
        {"icon": ICONS["combine"], "title": "Seamless Stream Concat", "description": "Repeats video and audio streams with zero gap or stutter."},
        {"icon": ICONS["video"], "title": "Visual Duration Calculation", "description": "Calculates new extended video duration automatically."},
        {"icon": ICONS["music"], "title": "Continuous Audio Loop", "description": "Audio repeats in rhythm with video frames."},
        {"icon": ICONS["shield"], "title": "Private & Secure", "description": "Processed safely on dedicated high-speed servers."},
        {"icon": ICONS["convert"], "title": "MP4 / MOV / WEBM", "description": "Save in universal video formats."},
        {"icon": ICONS["download"], "title": "Immediate Export", "description": "Download extended looped video right away."},
        {"icon": ICONS["check"], "title": "No Watermarks", "description": "100% free with clean, unbranded export."},
    ],
    "extract-frame": [
        {"icon": ICONS["camera"], "title": "High-Res Frame Grabber", "description": "Extract full-resolution uncompressed screenshots from any timestamp."},
        {"icon": ICONS["sliders"], "title": "Millisecond Precision", "description": "Scrub to the exact millisecond and grab the perfect still shot."},
        {"icon": ICONS["layers"], "title": "JPG & PNG Formats", "description": "Save screenshots in high quality JPEG or lossless PNG format."},
        {"icon": ICONS["video"], "title": "Real-Time Frame Preview", "description": "Preview still frames before downloading."},
        {"icon": ICONS["shield"], "title": "Private Cloud", "description": "Temporary snapshots deleted automatically after download."},
        {"icon": ICONS["zap"], "title": "Instant Extraction", "description": "Pulls pristine keyframe images in milliseconds."},
        {"icon": ICONS["download"], "title": "One-Click Image Download", "description": "Save full resolution photos directly to your device."},
        {"icon": ICONS["check"], "title": "Thumbnail & Poster Ready", "description": "Ideal for YouTube thumbnails, covers, and promotional banners."},
    ],
    "watermark": [
        {"icon": ICONS["camera"], "title": "Logo & Watermark Overlay", "description": "Protect your video intellectual property with logo watermarks."},
        {"icon": ICONS["sliders"], "title": "Opacity & Scaling", "description": "Adjust logo transparency and size percentage freely."},
        {"icon": ICONS["layers"], "title": "Corner & Center Positioning", "description": "Position in top-right, bottom-right, top-left, bottom-left, or center."},
        {"icon": ICONS["video"], "title": "Interactive Overlay Preview", "description": "Preview watermark placement over the video playback."},
        {"icon": ICONS["shield"], "title": "Secure File Handling", "description": "Uploaded logos and videos are automatically deleted after processing."},
        {"icon": ICONS["convert"], "title": "Universal Video Export", "description": "Export in MP4, MOV, WEBM, or MKV containers."},
        {"icon": ICONS["download"], "title": "High-Speed Render", "description": "Download your watermarked video in seconds."},
        {"icon": ICONS["check"], "title": "Transparent PNG Support", "description": "Flawless alpha channel rendering for professional logo blending."},
    ],
}

# Add alias mappings so all slug formats match
SLUG_ALIASES = {
    "trim_video": "trim",
    "merge_video": "merge",
    "crop_video": "crop",
    "resize_video": "resize",
    "rotate_video": "rotate",
    "flip_video": "flip",
    "speed_video": "speed",
    "compress_video": "compress",
    "convert_video": "convert",
    "video_to_gif": "video-to-gif",
    "gif_to_video": "gif-to-video",
    "remove_audio": "remove-audio",
    "extract_audio": "extract-audio",
    "change_volume": "change-volume",
    "reverse_video": "reverse",
    "fade_video": "fade",
    "effects_video": "effects",
    "fps_video": "fps",
    "loop_video": "loop",
    "extract_frame": "extract-frame",
    "frame": "extract-frame",
    "watermark_video": "watermark",
    "add_audio": "add-audio",
    "add_text": "add-text",
    "add_image": "add-image",
    "blur_video": "blur",
    "brighten_video": "brighten",
    "split_screen": "split-screen",
    "stabilize_video": "stabilize",
    "sync_audio": "sync-audio",
    "transition_video": "transition",
    "repair_video": "repair",
    "background_video": "background",
}


def get_tool_cards(tool_slug: str):
    """Return a list of eight rich card dicts for the given tool slug.
    Each card has 'icon' (SVG markup), 'title', and 'description'.
    """
    clean_slug = (tool_slug or "").strip().lower().replace("_", "-")
    canonical_slug = SLUG_ALIASES.get(tool_slug, SLUG_ALIASES.get(clean_slug, clean_slug))

    if canonical_slug in CARDS_DATA:
        return CARDS_DATA[canonical_slug]

    # Generate meaningful fallback cards for any unlisted slug
    readable_name = clean_slug.replace("-", " ").title()
    return _default_cards(readable_name, clean_slug.replace("-", " "))
