# Generated by Django 5.2.16 on 2026-07-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('audio', models.FileField(upload_to='audios/')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='output/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
