# Generated by Django 5.2.17 on 2026-09-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('audio', models.FileField(upload_to='audios/')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='output/')),
                ('mode', models.CharField(choices=[('replace', 'Replace Audio'), ('merge', 'Merge Audio')], default='replace', max_length=20)),
                ('volume', models.FloatField(default=1.0)),
                ('loop_audio', models.BooleanField(default=False)),
                ('start_time', models.CharField(default='00:00:00', max_length=20)),
                ('end_time', models.CharField(default='00:00:00', max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
