# Generated by Django 5.2.16 on 2026-07-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_replacement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoaudio',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='videoaudio',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='videoaudio',
            name='end_time',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='videoaudio',
            name='loop_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoaudio',
            name='mode',
            field=models.CharField(choices=[('replace', 'Replace Audio'), ('merge', 'Merge Audio')], default='replace', max_length=20),
        ),
        migrations.AddField(
            model_name='videoaudio',
            name='start_time',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='videoaudio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videoaudio',
            name='volume',
            field=models.FloatField(default=1.0),
        ),
    ]
