# Generated by Django 5.2.17 on 2026-09-10 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('source', models.CharField(choices=[('CONTACT', 'Contact'), ('HELP', 'Help')], default='CONTACT', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('category', models.CharField(max_length=80)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g. header, qr_code, analytics', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('BOOLEAN', 'Boolean (ON/OFF)'), ('NUMERIC', 'Numeric Limit'), ('UNLIMITED', 'Unlimited'), ('SELECT', 'Select (Text/Choice)'), ('DURATION', 'Duration (Text)')], default='BOOLEAN', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('section', models.CharField(default='SHORT URL', help_text='Section this feature belongs to', max_length=100)),
                ('is_public', models.BooleanField(default=True, help_text='Show on public pricing page')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('monthly_price', models.IntegerField(default=0)),
                ('yearly_price', models.IntegerField(default=0)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('contact', 'Contact Us')], default='fixed', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Plan description')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('setup_fee', models.IntegerField(default=0, help_text='Optional setup fee in INR')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default plan for new users?')),
                ('max_dynamic_qrs', models.IntegerField(default=5)),
                ('max_short_urls', models.IntegerField(default=10)),
                ('max_team_members', models.IntegerField(default=0)),
                ('max_domains', models.IntegerField(default=0)),
                ('max_api_requests', models.IntegerField(default=0)),
                ('analytics_access', models.BooleanField(default=False)),
                ('csv_export', models.BooleanField(default=False)),
                ('gps_tracking', models.BooleanField(default=False)),
                ('bulk_qr', models.BooleanField(default=False)),
                ('webhooks', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section header shown on pricing card', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='services.plan')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanSectionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature name, e.g. Short URLs', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional internal note')),
                ('feature_type', models.CharField(choices=[('BOOLEAN', 'Boolean (ON/OFF — shown as ✓ Feature Name)'), ('LIMIT', 'Limit (numeric value + label, e.g. 100 Short URLs / month)'), ('TEXT', 'Text (custom label, e.g. 30 Days Analytics History)'), ('UNLIMITED', 'Unlimited (shown as ✓ Unlimited Feature Name)')], default='BOOLEAN', max_length=20)),
                ('monthly_value', models.IntegerField(blank=True, help_text='Numeric value for monthly billing', null=True)),
                ('yearly_value', models.IntegerField(blank=True, help_text='Numeric value for yearly billing', null=True)),
                ('monthly_label', models.CharField(blank=True, max_length=255)),
                ('yearly_label', models.CharField(blank=True, max_length=255)),
                ('monthly_text', models.CharField(blank=True, max_length=255)),
                ('yearly_text', models.CharField(blank=True, max_length=255)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.plansection')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('price_at_purchase', models.IntegerField(default=0, help_text='Price stored at time of purchase')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('auto_renew', models.BooleanField(default=True)),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='services.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('gateway', models.CharField(default='Simulator', max_length=50)),
                ('payment_mode', models.CharField(default='Card', max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='services.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_code', models.CharField(max_length=50)),
                ('price_at_purchase', models.IntegerField(default=0)),
                ('billing_cycle', models.CharField(max_length=20)),
                ('features_data', models.JSONField(default=dict, help_text='Serialized dict of feature configurations at subscription time (audit only).')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='services.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='UsageOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=50)),
                ('additional_allowance', models.IntegerField(default=0)),
                ('override_limit', models.IntegerField(blank=True, help_text='Replaces the plan limit if set', null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_overrides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Whether this feature is enabled for this plan')),
                ('monthly_limit', models.IntegerField(blank=True, help_text='Monthly usage limit', null=True)),
                ('yearly_limit', models.IntegerField(blank=True, help_text='Yearly usage limit', null=True)),
                ('is_unlimited', models.BooleanField(default=False, help_text='If True, ignore limit entirely for all billing cycles')),
                ('history_days', models.IntegerField(blank=True, help_text='For analytics feature: how many days of history are accessible', null=True)),
                ('value_boolean', models.BooleanField(default=False)),
                ('value_numeric', models.IntegerField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='services.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='services.plan')),
            ],
            options={
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(db_index=True, max_length=50)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('current_usage', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feature_key', 'period_start')},
            },
        ),
    ]
