# Generated by Django 5.2.17 on 2026-08-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_feature_plan_description_plan_display_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="pricing_type",
            field=models.CharField(
                choices=[("fixed", "Fixed Price"), ("contact", "Contact Us")],
                default="fixed",
                max_length=20,
            ),
        ),
    ]
