# Generated by Django 5.2.17 on 2026-08-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_plan_pricing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_public",
            field=models.BooleanField(
                default=True, help_text="Show on public pricing page"
            ),
        ),
        migrations.CreateModel(
            name="PlanSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Section heading, e.g. SHORT URL", max_length=100
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="services.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PlanFeatureItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Feature name, e.g. 'Short URLs'", max_length=100
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("BOOLEAN", "Boolean (Yes/No Feature)"),
                            ("LIMIT", "Limit (Monthly & Yearly Value)"),
                            ("UNLIMITED", "Unlimited"),
                            ("TEXT", "Custom Text"),
                        ],
                        default="BOOLEAN",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_value",
                    models.IntegerField(
                        blank=True, help_text="Monthly numeric limit", null=True
                    ),
                ),
                (
                    "yearly_value",
                    models.IntegerField(
                        blank=True, help_text="Yearly numeric limit", null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Display unit for LIMIT type, e.g. 'Short URLs'. Defaults to name.",
                        max_length=100,
                    ),
                ),
                (
                    "unlimited",
                    models.BooleanField(
                        default=False,
                        help_text="Treat this feature as unlimited regardless of type",
                    ),
                ),
                (
                    "display_mode",
                    models.CharField(
                        choices=[
                            ("AUTO", "Auto (System Generated)"),
                            ("CUSTOM", "Custom Text Override"),
                        ],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                (
                    "custom_display_text",
                    models.CharField(
                        blank=True,
                        help_text="Used when display_mode=CUSTOM or for BOOLEAN/TEXT features",
                        max_length=255,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="check",
                        help_text="Lucide icon name",
                        max_length=50,
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(
                        blank=True,
                        help_text="Limit service key, e.g. 'short_urls'. Links this feature to backend enforcement.",
                        max_length=50,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_items",
                        to="services.plansection",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
