# Generated by Django 5.2.17 on 2026-08-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_plan_is_public_plansection_planfeatureitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plansection",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="is_public",
        ),
        migrations.DeleteModel(
            name="PlanFeatureItem",
        ),
        migrations.DeleteModel(
            name="PlanSection",
        ),
    ]
