# Generated by Django 5.2.17 on 2026-08-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_remove_plansection_plan_remove_plan_is_public_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Section header shown on pricing card, e.g. SHORT URL",
                        max_length=100,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="services.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PlanSectionFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Feature name, e.g. Short URLs", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional internal note"),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("BOOLEAN", "Boolean (ON/OFF — shown as ✓ Feature Name)"),
                            (
                                "LIMIT",
                                "Limit (numeric value + label, e.g. 100 Short URLs / month)",
                            ),
                            (
                                "TEXT",
                                "Text (custom label, e.g. 30 Days Analytics History)",
                            ),
                            (
                                "UNLIMITED",
                                "Unlimited (shown as ✓ Unlimited Feature Name)",
                            ),
                        ],
                        default="BOOLEAN",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Numeric value for monthly billing",
                        null=True,
                    ),
                ),
                (
                    "yearly_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Numeric value for yearly billing",
                        null=True,
                    ),
                ),
                (
                    "monthly_label",
                    models.CharField(
                        blank=True,
                        help_text="Full label for monthly display, e.g. Short URLs / month",
                        max_length=255,
                    ),
                ),
                (
                    "yearly_label",
                    models.CharField(
                        blank=True,
                        help_text="Full label for yearly display, e.g. Short URLs / year",
                        max_length=255,
                    ),
                ),
                (
                    "monthly_text",
                    models.CharField(
                        blank=True,
                        help_text="Text value for monthly (TEXT type)",
                        max_length=255,
                    ),
                ),
                (
                    "yearly_text",
                    models.CharField(
                        blank=True,
                        help_text="Text value for yearly (TEXT type)",
                        max_length=255,
                    ),
                ),
                (
                    "is_unlimited",
                    models.BooleanField(
                        default=False,
                        help_text="If True, displays as Unlimited regardless of values",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="services.plansection",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
