# Generated by Django 5.2.17 on 2026-08-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_plansection_plansectionfeature"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=100)),
                ("plan_code", models.CharField(max_length=50)),
                ("price_at_purchase", models.IntegerField(default=0)),
                ("billing_cycle", models.CharField(max_length=20)),
                (
                    "features_data",
                    models.JSONField(
                        default=dict,
                        help_text="Serialized dict of feature configurations: { 'short_urls': {'enabled': True, 'limit': 1500, 'is_unlimited': False}, ... }",
                    ),
                ),
                ("snapshot_date", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="services.subscription",
                    ),
                ),
            ],
        ),
    ]
