# Generated by Django 5.2.17 on 2026-09-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_subscriptionsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansectionfeature',
            name='feature_key',
            field=models.CharField(blank=True, help_text='Internal registry key (e.g. custom_header)', max_length=50, null=True),
        ),
    ]
