# Generated by Django 5.2.17 on 2026-09-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_plansectionfeature_feature_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansectionfeature',
            name='feature_key',
        ),
    ]
