# Generated by Django 5.2.17 on 2026-09-05 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_seed_feature_master_and_plan_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='key',
            field=models.CharField(help_text='e.g. header, qr_code, analytics', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='services.plan'),
        ),
        migrations.AlterField(
            model_name='plansection',
            name='name',
            field=models.CharField(help_text='Section header shown on pricing card', max_length=100),
        ),
        migrations.AlterField(
            model_name='plansectionfeature',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plansectionfeature',
            name='monthly_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plansectionfeature',
            name='monthly_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plansectionfeature',
            name='yearly_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plansectionfeature',
            name='yearly_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptionsnapshot',
            name='features_data',
            field=models.JSONField(default=dict, help_text='Serialized dict of feature configurations at subscription time (audit only).'),
        ),
    ]
