# Generated by Django 5.2.17 on 2026-09-05 08:59

from django.db import migrations, models

def migrate_limits(apps, schema_editor):
    PlanFeature = apps.get_model('services', 'PlanFeature')
    for pf in PlanFeature.objects.all():
        if getattr(pf, 'limit', None) is not None:
            pf.monthly_limit = pf.limit
            pf.yearly_limit = pf.limit * 10
        pf.save(update_fields=['monthly_limit', 'yearly_limit'])

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_feature_key_alter_planfeature_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeature',
            name='monthly_limit',
            field=models.IntegerField(blank=True, help_text='Monthly usage limit', null=True),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='yearly_limit',
            field=models.IntegerField(blank=True, help_text='Yearly usage limit', null=True),
        ),
        migrations.RunPython(migrate_limits, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='planfeature',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='planfeature',
            name='limit_period',
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='is_unlimited',
            field=models.BooleanField(default=False, help_text='If True, ignore limit entirely for all billing cycles'),
        ),
    ]
