from django import forms

from .base import BaseVideoForm


class CropVideoForm(BaseVideoForm):
    """
    Form for cropping a video.

    Crop coordinates are generated by JavaScript
    from the realtime crop editor.
    """

    x = forms.IntegerField(
        required=True,
        min_value=0,
        widget=forms.HiddenInput(),
    )

    y = forms.IntegerField(
        required=True,
        min_value=0,
        widget=forms.HiddenInput(),
    )

    width = forms.IntegerField(
        required=True,
        min_value=2,
        widget=forms.HiddenInput(),
    )

    height = forms.IntegerField(
        required=True,
        min_value=2,
        widget=forms.HiddenInput(),
    )

    def clean(self):
        try:
            cleaned_data = super().clean()

            x = cleaned_data.get("x")
            y = cleaned_data.get("y")
            width = cleaned_data.get("width")
            height = cleaned_data.get("height")

            if None in (
                x,
                y,
                width,
                height,
            ):
                return cleaned_data

            if x < 0:
                raise forms.ValidationError(
                    "Crop position cannot be negative."
                )

            if y < 0:
                raise forms.ValidationError(
                    "Crop position cannot be negative."
                )

            if width < 2:
                raise forms.ValidationError(
                    "Crop width is too small."
                )

            if height < 2:
                raise forms.ValidationError(
                    "Crop height is too small."
                )

            return cleaned_data

        except forms.ValidationError:
            raise

        except Exception as exc:
            raise forms.ValidationError(
                "Unable to validate crop settings."
            ) from exc




class ResizeVideoForm(forms.Form):
    """
    Form for resizing a video with editor settings.
    """

    video = forms.FileField(
        required=True,
    )

    width = forms.IntegerField(
        required=True,
        min_value=2,
    )

    height = forms.IntegerField(
        required=True,
        min_value=2,
    )

    aspect_ratio = forms.CharField(
        required=False,
        max_length=20,
    )

    fit_mode = forms.ChoiceField(
        required=False,
        choices=[
            ("fit", "Fit"),
            ("fill", "Fill"),
        ],
    )

    zoom = forms.FloatField(
        required=False,
        min_value=0.1,
        max_value=5.0,
    )

    position_x = forms.IntegerField(
        required=False,
    )

    position_y = forms.IntegerField(
        required=False,
    )

    background_color = forms.CharField(
        required=False,
        max_length=20,
    )

    output_format = forms.ChoiceField(
        required=False,
        choices=[
            ("mp4", "MP4"),
            ("mov", "MOV"),
            ("webm", "WEBM"),
            ("avi", "AVI"),
            ("mkv", "MKV"),
            ("gif", "GIF"),
            ("m4v", "M4V"),
        ],
    )

    def clean_zoom(self):
        zoom = self.cleaned_data.get("zoom")

        if zoom is None:
            return 1.0

        if zoom < 0.1:
            raise forms.ValidationError(
                "Zoom must be at least 0.1."
            )

        if zoom > 5:
            raise forms.ValidationError(
                "Zoom cannot exceed 5."
            )

        return zoom

    def clean_background_color(self):
        color = self.cleaned_data.get(
            "background_color"
        )

        if not color:
            return "#000000"

        color = color.strip()

        if not color.startswith("#"):
            raise forms.ValidationError(
                "Invalid background color."
            )

        if len(color) not in (4, 7):
            raise forms.ValidationError(
                "Invalid background color."
            )

        return color

    def clean_output_format(self):
        output_format = (
            self.cleaned_data.get(
                "output_format"
            )
        )

        return output_format or "mp4"